env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  
rules: {
        import/prefer-default-export: off,
        no-console: off,
        no-restricted-syntax: [
            error,
            {
               selector: "CallExpression[callee.object.name='console'][callee.property.name!=/^(log|warn|error|info|trace)$/]",
                message: "Unexpected property on console object was called"
            }
        ],
       import/extensions: [
         error,
        ignorePackages,
        {
          .js: never,
          .jsx: never,
          .ts: never,
          .tsx: never
        }
       ] 
       
 }
      

